apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie  # Changed to lowercase
spec:
  selector:
    matchLabels:
      app: movie  # Changed to lowercase
  replicas: 1
  template:
    metadata:
      labels:
        app: movie  # Changed to lowercase
    spec:
      containers:
      - name: fullstack
        image: manojkrishnappa/movie:6
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        # Adding health checks (customize the path and port as needed)
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: movie-service  # Changed to lowercase
spec:
  selector:
    app: movie  # Changed to lowercase
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer
