apiVersion: apps/v1
kind: Deployment
metadata:
  name: Movie
spec:
  selector:
    matchLabels:
      app: Movie
  replicas: 1
  template:
    metadata:
      labels:
        app: Movie
    spec:
      containers:
<<<<<<< HEAD
      - name: Movie
        image: manojkrishnappa/movie:replaceImageTag
=======
      - name: fullstack
        image: manojkrishnappa/movie:2
>>>>>>> 50140dd02d30e746090bdfccbc9511d0663ec41c
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        # Adding health checks (customize the path and port as needed)
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: fullstack-service  # Updated name for clarity
spec:
  selector:
    app: fullstack
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer